In [5]:
import pandas as pd
from pykrx import stock
from pykrx import bond
from time import sleep

from datetime import datetime
import os
import time

import glob


# 경로 변경
os.chdir('/home/shjj08choi/finance_mlops')

In [10]:
kor_index_list_df = pd.read_csv('data_crawler/kor_index_list_df/kor_index_list_df_20230825.csv')

In [14]:
index_code_master = pd.read_csv('data_crawler/index_code_master/index_code_master_20230825.csv', dtype = {'ticker': object})

In [18]:
kor_index_ohlcv = pd.read_csv('data_crawler/kor_index_ohlcv/kor_index_ohlcv_20230825.csv', dtype = {'ticker': object})

In [19]:
kor_index_ohlcv

,date,open,high,low,close,volume,trading_value,market_cap,index_code
0,2018-01-02,2474.86,2481.02,2465.94,2479.65,262205431,4786386686165,1613508196692261,1001
1,2018-01-03,2484.63,2493.40,2481.91,2486.35,331094681,6019622040484,1617634317727445,1001
2,2018-01-04,2502.50,2502.50,2466.45,2466.46,333836328,6896287056563,1604916139690676,1001
3,2018-01-05,2476.85,2497.52,2475.51,2497.52,308769669,6317518427311,1624970533116195,1001
4,2018-01-08,2510.70,2515.37,2494.18,2513.28,311429324,6404885697956,1634777680824259,1001
...,...,...,...,...,...,...,...,...,...
134011,2023-08-21,2839.67,2856.25,2791.74,2794.01,3558831,187023003660,21857810315930,2218
134012,2023-08-22,2801.79,2820.50,2781.86,2795.58,3189192,171057095440,21888327695220,2218
134013,2023-08-23,2800.19,2810.70,2729.68,2734.42,5143980,250349340860,21332623929290,2218
134014,2023-08-24,2760.93,2780.64,2740.08,2760.04,3462347,157476015815,21536697255290,2218
134015,2023-08-25,2730.54,2774.03,2714.73,2743.58,2652407,128819166075,21411017678170,2218

In [22]:
kor_index_ohlcv[kor_index_ohlcv['date'] == '2023-08-25']

,date,open,high,low,close,volume,trading_value,market_cap,index_code
1393,2023-08-25,2505.39,2526.37,2502.05,2519.14,577383852,8302851242350,1997701491140052,1001
2787,2023-08-25,2494.74,2516.28,2491.40,2507.98,55647503,4399031565690,1593598498796970,1002
4181,2023-08-25,2718.35,2742.71,2714.65,2740.06,45927663,1213406263816,236168085809167,1003
5575,2023-08-25,2342.81,2352.65,2340.16,2349.81,455459959,2457402560897,95162617500665,1004
6969,2023-08-25,3613.56,3665.79,3603.84,3661.42,100196699,384584294334,25670516728536,1005
...,...,...,...,...,...,...,...,...,...
128439,2023-08-25,601.37,617.18,597.92,609.85,6651721,42336433955,3479657347580,2214
129833,2023-08-25,786.12,792.14,779.96,788.45,4715189,46884260155,6108353819210,2215
131227,2023-08-25,759.12,773.04,756.31,771.37,46790000,2053260373943,53707973314440,2216
132621,2023-08-25,2485.69,2505.06,2474.83,2485.84,20023114,635817372145,50005892102240,2217
134015,2023-08-25,2730.54,2774.03,2714.73,2743.58,2652407,128819166075,21411017678170,2218

In [17]:
index_code_master[index_code_master['index_code'] == 1008]

      ticker  index_code index_code_nm market corp_name
1729  051910        1008            화학  KOSPI      LG화학
1730  096770        1008            화학  KOSPI   SK이노베이션
1731  010950        1008            화학  KOSPI     S-Oil
1732  090430        1008            화학  KOSPI    아모레퍼시픽
1733  001570        1008            화학  KOSPI        금양
...      ...         ...           ...    ...       ...
1827  006380        1008            화학  KOSPI       카프로
1828  051630        1008            화학  KOSPI      진양화학
1829  024070        1008            화학  KOSPI    WISCOM
1830  010640        1008            화학  KOSPI      진양폴리
1831  025620        1008            화학  KOSPI   제이준코스메틱

[103 rows x 5 columns]

In [24]:
df[df['market'] == 'KOSDAQ']

    index_code      index_code_nm  market
46        2001                코스닥  KOSDAQ
47        2002            코스닥 대형주  KOSDAQ
48        2003            코스닥 중형주  KOSDAQ
49        2004            코스닥 소형주  KOSDAQ
50        2012              기타서비스  KOSDAQ
51        2015             코스닥 IT  KOSDAQ
52        2024                제조업  KOSDAQ
53        2026                 건설  KOSDAQ
54        2027                 유통  KOSDAQ
55        2029                 운송  KOSDAQ
56        2031                 금융  KOSDAQ
57        2037              오락·문화  KOSDAQ
58        2041            통신방송서비스  KOSDAQ
59        2042       IT S/W & SVC  KOSDAQ
60        2043             IT H/W  KOSDAQ
61        2056             음식료·담배  KOSDAQ
62        2058              섬유·의류  KOSDAQ
63        2062              종이·목재  KOSDAQ
64        2063            출판·매체복제  KOSDAQ
65        2065                 화학  KOSDAQ
66        2066                 제약  KOSDAQ
67        2067                비금속  KOSDAQ
68        2068                 금속  KOSDAQ
69        2070              기계·장비  KOSDAQ
70        2072             일반전기전자  KOSDAQ
71        2074            의료·정밀기기  KOSDAQ
72        2075            운송장비·부품  KOSDAQ
73        2077               기타제조  KOSDAQ
74        2151              통신서비스  KOSDAQ
75        2152              방송서비스  KOSDAQ
76        2153                인터넷  KOSDAQ
77        2154             디지털컨텐츠  KOSDAQ
78        2155              소프트웨어  KOSDAQ
79        2156             컴퓨터서비스  KOSDAQ
80        2157               통신장비  KOSDAQ
81        2158               정보기기  KOSDAQ
82        2159                반도체  KOSDAQ
83        2160               IT부품  KOSDAQ
84        2181          코스닥 우량기업부  KOSDAQ
85        2182          코스닥 벤처기업부  KOSDAQ
86        2183          코스닥 중견기업부  KOSDAQ
87        2184        코스닥 기술성장기업부  KOSDAQ
88        2189            코스닥 글로벌  KOSDAQ
89        2203            코스닥 150  KOSDAQ
90        2212         코스닥 150 소재  KOSDAQ
91        2213        코스닥 150 산업재  KOSDAQ
92        2214      코스닥 150 필수소비재  KOSDAQ
93        2215      코스닥 150 자유소비재  KOSDAQ
94        2216       코스닥 150 정보기술  KOSDAQ
95        2217       코스닥 150 헬스케어  KOSDAQ
96        2218  코스닥 150 커뮤니케이션서비스  KOSDAQ