In [3]:
import plotly.graph_objects as go

from ta.trend import MACD
from ta.momentum import StochasticOscillator

import numpy as np
import pandas as pd
from pykrx import stock
from pykrx import bond
from time import sleep

from datetime import datetime
from datetime import timedelta
import os
import time
from plotly.subplots import make_subplots
import glob

from pyarrow import csv
import pyarrow as pa
import pyarrow.parquet as pq

In [4]:
os.chdir('/home/shjj08choi4/finance_mlops')

In [5]:
parquet_list = glob.glob('data_crawler/cleaning/kor_stock_ohlcv/*')

In [6]:
parquet_list

['data_crawler/cleaning/kor_stock_ohlcv/df_raw_anal_total_2_KOSDAQ_20240107.parquet',
 'data_crawler/cleaning/kor_stock_ohlcv/df_raw_anal_total_2_KOSPI_20240107.parquet',
 'data_crawler/cleaning/kor_stock_ohlcv/df_raw_total_2_KOSDAQ_20240107.parquet',
 'data_crawler/cleaning/kor_stock_ohlcv/df_raw_total_2_KOSPI_20240107.parquet']

In [9]:
t = pq.read_table(parquet_list[2])
df = t.to_pandas()

In [10]:
df

,date,open,high,low,close,volume,price_change_percentage,ticker,corp_name,market,...,MACD_Signal,변화량,상승폭,하락폭,AU,AD,RSI,MA5-20,MA20-60,MA60-120
0,2023-01-25 00:00:00+00:00,10390,10400,10120,10240.0,109373,2.400000,051360,토비스,KOSDAQ,...,NaN,1280.0,1280.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-05-26 00:00:00+00:00,11720,11820,11410,11520.0,194936,-1.706485,051360,토비스,KOSDAQ,...,NaN,1280.0,1280.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-04-17 00:00:00+00:00,11040,11930,10930,11520.0,996802,4.632153,051360,토비스,KOSDAQ,...,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-10-26 00:00:00+00:00,16410,16870,16130,16640.0,120415,-1.187648,051360,토비스,KOSDAQ,...,NaN,5120.0,5120.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-04-14 00:00:00+00:00,10820,11140,10690,11010.0,189906,1.662050,051360,토비스,KOSDAQ,...,NaN,1280.0,1280.0,0.0,710.759387,483.779411,59.500737,615.5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103120,2023-04-13 00:00:00+00:00,19960,20400,19350,20200.0,399829,1.202405,211270,AP위성,KOSDAQ,...,408.119460,1950.0,1950.0,0.0,1540.913762,939.452955,62.124433,2878.0,1543.500000,183.500000
103121,2023-05-02 00:00:00+00:00,16890,17920,16890,17310.0,290123,2.486679,211270,AP위성,KOSDAQ,...,-435.339597,4060.0,4060.0,0.0,1458.286735,957.790129,60.357630,846.5,-1178.666667,121.250000
103122,2023-11-14 00:00:00+00:00,13820,14950,13600,14600.0,1111549,6.413994,211270,AP위성,KOSDAQ,...,14.775069,5260.0,5260.0,0.0,1260.387698,1000.838431,55.739127,-384.0,-466.166667,-390.416667
103123,2023-09-15 00:00:00+00:00,14590,15550,14250,14700.0,1200544,2.439024,211270,AP위성,KOSDAQ,...,-486.698135,3850.0,3850.0,0.0,1194.058005,869.146521,57.873952,-1221.5,358.500000,-212.500000
103124,2023-03-23 00:00:00+00:00,23550,24300,21200,22500.0,1824604,-5.063291,211270,AP위성,KOSDAQ,...,-0.170012,4900.0,4900.0,0.0,1571.917362,749.417154,67.716107,3373.5,127.166667,150.833333

In [27]:
df['ticker'].unique()

array(['060310', '054620', '265520', ..., '189980', '037440', '238490'],
      dtype=object)

In [ ]:
t = pq.read_table('df.parquet')
df = t.to_pandas()